name: Discord Notifier

on:
  release:
    types: [published]

jobs:
  discord:
    name: Discord Message
    runs-on: "ubuntu-latest"
    steps:
      - name: Post to Discord Webhook
        uses: sebastianpopp/discord-action@releases/v2
        with:
          # A full discord webhook url
          webhook: https://discord.com/api/webhooks/1121737264951726166/egJVjKXFy0Qx5Fs0ABEP60DWuUPegyBtMbQTTCJwzHVMeZF8Hjsl4zgs0W6hzBMnYguS

          # Message title
          message-title: New Release Created
